//go:build linux

package collector

import (
	"bytes"
	"context"
	"encoding/binary"
	"errors"
	"fmt"
	"strings"
	"sync"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/perf"
	"go.uber.org/zap"

	"github.com/imkerbos/mxsec-platform/internal/agent/edr/event"
)

// BPF event type constants — must match bpf/common.h
const (
	bpfEventProcessExec = 1
	bpfEventProcessExit = 2
)

// processEvent mirrors struct process_event from bpf/common.h.
// Field order, sizes, and padding MUST stay in sync with the C struct.
// Verified against bpf2go-generated processProcessEvent in process_bpfel.go.
// All fields are exported because binary.Read uses reflect and cannot write unexported fields.
type processEvent struct {
	EventType   uint8
	Pad0        [3]uint8
	Pid         uint32
	Tgid        uint32
	Ppid        uint32
	Uid         uint32
	Gid         uint32
	ExitCode    int32
	Pad1        [4]byte   // alignment padding for 8-byte StartTs
	StartTs     uint64
	InContainer uint8
	Pad2        [7]uint8
	Comm        [16]byte
	Filename    [256]byte
	Cmdline     [512]byte
}

// ebpfCollector implements Collector using cilium/ebpf for kernel-level event collection.
//
// Lifecycle:
//   1. newEBPFCollector() — no BPF objects loaded yet
//   2. Start() — load BPF objects, attach tracepoints, start perf reader
//   3. Stop()  — detach tracepoints, close perf reader, release BPF resources
type ebpfCollector struct {
	logger  *zap.Logger
	eventCh chan *event.Event

	// BPF resources (nil until Start)
	objs       *processObjects // generated by bpf2go
	execLink   link.Link
	exitLink   link.Link
	perfReader *perf.Reader

	wg sync.WaitGroup
}

func newEBPFCollector(logger *zap.Logger) (*ebpfCollector, error) {
	return &ebpfCollector{
		logger: logger,
	}, nil
}

func (c *ebpfCollector) Mode() Mode {
	return ModeEBPF
}

func (c *ebpfCollector) Capabilities() []Capability {
	return []Capability{
		CapEBPFFull,
		CapFileFull,
		CapContainerCtx,
	}
}

// Start loads BPF programs, attaches tracepoints, and begins reading events.
func (c *ebpfCollector) Start(ctx context.Context) (<-chan *event.Event, error) {
	c.eventCh = make(chan *event.Event, 4096)

	// Step 1: Load compiled BPF objects (embedded bytecode from bpf2go).
	objs := &processObjects{}
	if err := loadProcessObjects(objs, &ebpf.CollectionOptions{
		Programs: ebpf.ProgramOptions{
			LogLevel: ebpf.LogLevelInstruction, // verbose verifier log on failure
		},
	}); err != nil {
		close(c.eventCh)
		return nil, fmt.Errorf("load BPF objects: %w", err)
	}
	c.objs = objs

	// Step 2: Attach raw tracepoints.
	execLink, err := link.AttachRawTracepoint(link.RawTracepointOptions{
		Name:    "sched_process_exec",
		Program: objs.TracepointSchedProcessExec,
	})
	if err != nil {
		objs.Close()
		close(c.eventCh)
		return nil, fmt.Errorf("attach sched_process_exec: %w", err)
	}
	c.execLink = execLink

	exitLink, err := link.AttachRawTracepoint(link.RawTracepointOptions{
		Name:    "sched_process_exit",
		Program: objs.TracepointSchedProcessExit,
	})
	if err != nil {
		execLink.Close()
		objs.Close()
		close(c.eventCh)
		return nil, fmt.Errorf("attach sched_process_exit: %w", err)
	}
	c.exitLink = exitLink

	// Step 3: Open perf reader on the events map.
	// Buffer size: 16 pages (64 KiB). Each process_event is ~812 bytes,
	// so this holds ~80 events before needing drain. Our reader goroutine
	// drains continuously, so this is ample headroom.
	reader, err := perf.NewReader(objs.Events, 16*4096)
	if err != nil {
		exitLink.Close()
		execLink.Close()
		objs.Close()
		close(c.eventCh)
		return nil, fmt.Errorf("create perf reader: %w", err)
	}
	c.perfReader = reader

	// Step 4: Start reader goroutine.
	c.wg.Add(1)
	go c.readEvents(ctx)

	c.logger.Info("eBPF collector started",
		zap.String("exec_tp", "sched_process_exec"),
		zap.String("exit_tp", "sched_process_exit"),
	)

	return c.eventCh, nil
}

// Stop detaches all BPF programs and releases resources.
func (c *ebpfCollector) Stop() error {
	// Close perf reader first — this unblocks readEvents goroutine.
	if c.perfReader != nil {
		c.perfReader.Close()
	}

	// Wait for reader goroutine to finish.
	c.wg.Wait()

	// Detach tracepoints.
	if c.exitLink != nil {
		c.exitLink.Close()
	}
	if c.execLink != nil {
		c.execLink.Close()
	}

	// Release BPF objects (programs + maps).
	if c.objs != nil {
		c.objs.Close()
	}

	c.logger.Info("eBPF collector resources released")
	return nil
}

// readEvents is the perf buffer reader goroutine. It reads raw BPF events,
// decodes them, converts to event.Event, and sends to eventCh.
func (c *ebpfCollector) readEvents(ctx context.Context) {
	defer c.wg.Done()
	defer close(c.eventCh)

	for {
		record, err := c.perfReader.Read()
		if err != nil {
			if errors.Is(err, perf.ErrClosed) {
				// Normal shutdown path — perfReader.Close() was called.
				return
			}
			c.logger.Warn("perf reader error", zap.Error(err))
			continue
		}

		if record.LostSamples > 0 {
			c.logger.Warn("perf buffer lost samples",
				zap.Uint64("lost", record.LostSamples),
			)
			continue
		}

		evt, err := c.decodeProcessEvent(record.RawSample)
		if err != nil {
			c.logger.Debug("failed to decode BPF event", zap.Error(err))
			continue
		}

		// Non-blocking send: if channel is full, drop event and log.
		// This prevents a slow consumer from blocking the BPF pipeline.
		select {
		case c.eventCh <- evt:
		case <-ctx.Done():
			return
		default:
			c.logger.Warn("event channel full, dropping event",
				zap.String("event_type", string(evt.EventType)),
			)
		}
	}
}

// decodeProcessEvent parses a raw BPF perf event sample into an event.Event.
func (c *ebpfCollector) decodeProcessEvent(raw []byte) (*event.Event, error) {
	var pe processEvent
	if err := binary.Read(bytes.NewReader(raw), binary.LittleEndian, &pe); err != nil {
		return nil, fmt.Errorf("binary decode: %w", err)
	}

	// Extract NUL-terminated strings from fixed-size byte arrays.
	comm := cString(pe.Comm[:])
	filename := cString(pe.Filename[:])
	cmdline := cmdlineString(pe.Cmdline[:])

	switch pe.EventType {
	case bpfEventProcessExec:
		evt := event.NewProcessExec(
			int(pe.Tgid), // pid in userspace = tgid in kernel
			int(pe.Ppid),
			filename,
			cmdline,
		)
		evt.SetField("uid", fmt.Sprintf("%d", pe.Uid))
		evt.SetField("gid", fmt.Sprintf("%d", pe.Gid))
		evt.SetField("comm", comm)
		evt.SetField("ktime_ns", fmt.Sprintf("%d", pe.StartTs))
		if pe.InContainer == 1 {
			evt.SetField("in_container", "true")
		}
		return evt, nil

	case bpfEventProcessExit:
		evt := event.NewProcessExit(
			int(pe.Tgid),
			int(pe.ExitCode),
		)
		evt.SetField("ppid", fmt.Sprintf("%d", pe.Ppid))
		evt.SetField("uid", fmt.Sprintf("%d", pe.Uid))
		evt.SetField("comm", comm)
		evt.SetField("ktime_ns", fmt.Sprintf("%d", pe.StartTs))
		if pe.InContainer == 1 {
			evt.SetField("in_container", "true")
		}
		return evt, nil

	default:
		return nil, fmt.Errorf("unknown BPF event type: %d", pe.EventType)
	}
}

// cString extracts a NUL-terminated string from a byte slice.
func cString(b []byte) string {
	if i := bytes.IndexByte(b, 0); i >= 0 {
		b = b[:i]
	}
	return strings.TrimSpace(string(b))
}

// cmdlineString converts a NUL-separated cmdline byte slice into a space-separated string.
// Kernel cmdline args are stored as: "arg0\0arg1\0arg2\0"
func cmdlineString(b []byte) string {
	// Find the effective end (first double-NUL or end of buffer)
	end := len(b)
	if i := bytes.IndexByte(b, 0); i >= 0 {
		// Find the last non-NUL byte
		for end > 0 && b[end-1] == 0 {
			end--
		}
	}
	if end == 0 {
		return ""
	}
	// Replace internal NULs with spaces
	result := make([]byte, end)
	copy(result, b[:end])
	for i := range result {
		if result[i] == 0 {
			result[i] = ' '
		}
	}
	return strings.TrimSpace(string(result))
}

// String implements fmt.Stringer for logging.
func (c *ebpfCollector) String() string {
	return fmt.Sprintf("ebpf-collector(mode=%s)", c.Mode())
}
